#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TMPuzzleXForms.Droid.Resource", IsApplication=true)]

namespace TMPuzzleXForms.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon72x72 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int MarkBlue = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int MarkGreen = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int MarkNone = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int MarkOrange = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int MarkPurple = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int MarkRed = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
	}
}
#pragma warning restore 1591
